blueprint:
  name: Zigbee2MQTT - Tuya TS004F 4-Button 12 scene switch 
  description: Make use of your TS004F inside of the 12-scene mode. Mine was shipped as a dimmer. If you follow the instructions from the Zigbee2mqtt, you can change the device's internal profile. https://www.zigbee2mqtt.io/devices/TS004F.html
  domain: automation
  input:
    switch:
      name: TS004F Switch
      description: Tuya 4-Button Scene Switch to use
      selector:
        entity:
          domain: sensor
          integration: mqtt
    button_1_single_press:
      name: Single Press - Button 1
      description: Action to run on button 1 (upper-left) single press
      default: []
      selector:
        action: {}
    button_1_double_press:
      name: Double Press - Button 1
      description: Action to run on button 1 (upper-left) double press
      default: []
      selector:
        action: {}
    button_1_held:
      name: Hold - Button 1
      description: Action to run on button 1 (upper-left) held for 5 seconds
      default: []
      selector:
        action: {}
    button_2_single_press:
      name: Single Press - Button 2
      description: Action to run on button 2 (upper-right) single press
      default: []
      selector:
        action: {}
    button_2_double_press:
      name: Double Press - Button 2
      description: Action to run on button 2 (upper-right) double press
      default: []
      selector:
        action: {}
    button_2_held:
      name: Hold - Button 2
      description: Action to run on button 2 (upper-right) held for 5 seconds
      default: []
      selector:
        action: {}
    button_3_single_press:
      name: Single Press - Button 3
      description: Action to run on button 3 (bottom-left) single press
      default: []
      selector:
        action: {}
    button_3_double_press:
      name: Double Press - Button 3
      description: Action to run on button 3 (bottom-left) double press
      default: []
      selector:
        action: {}
    button_3_held:
      name: Hold - Button 3
      description: Action to run on button 3 (bottom-left) held for 5 seconds
      default: []
      selector:
        action: {}
    button_4_single_press:
      name: Single Press - Button 4
      description: Action to run on button 4 (bottom-right) single press
      default: []
      selector:
        action: {}
    button_4_double_press:
      name: Double Press - Button 4
      description: Action to run on button 4 (bottom-right) double press
      default: []
      selector:
        action: {}
    button_4_held:
      name: Hold - Button 4
      description: Action to run on button 4 (bottom-right) held for 5 seconds
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent
variables:
  command: '{{ trigger.to_state.state }}'
trigger:
- platform: state
  entity_id: !input 'switch'
  to:
    - '1_single'
    - '1_double'
    - '1_hold'
    - '2_single'
    - '2_double'
    - '2_hold'
    - '3_single'
    - '3_double'
    - '3_hold'
    - '4_single'
    - '4_double'
    - '4_hold'
action:
  - choose:
    - conditions:
      - '{{ command == ''1_single'' }}'
      sequence: !input 'button_1_single_press'
    - conditions:
      - '{{ command == ''1_double'' }}'
      sequence: !input 'button_1_double_press'
    - conditions:
      - '{{ command == ''1_hold'' }}'
      sequence: !input 'button_1_held'
    - conditions:
      - '{{ command == ''2_single'' }}'
      sequence: !input 'button_2_single_press'
    - conditions:
      - '{{ command == ''2_double'' }}'
      sequence: !input 'button_2_double_press'
    - conditions:
      - '{{ command == ''2_hold'' }}'
      sequence: !input 'button_2_held'
    - conditions:
      - '{{ command == ''3_single'' }}'
      sequence: !input 'button_3_single_press'
    - conditions:
      - '{{ command == ''3_double'' }}'
      sequence: !input 'button_3_double_press'
    - conditions:
      - '{{ command == ''3_hold'' }}'
      sequence: !input 'button_3_held'
    - conditions:
      - '{{ command == ''4_single'' }}'
      sequence: !input 'button_4_single_press'
    - conditions:
      - '{{ command == ''4_double'' }}'
      sequence: !input 'button_4_double_press'
    - conditions:
      - '{{ command == ''4_hold'' }}'
      sequence: !input 'button_4_held'